#!/bin/bash

# backup_jots
# Push local entries to S3, then pull entries from S3
# Author: Phaedrus

# Pull jot coniguration
source ./config

printf "\nPushing to S3...\n"
aws s3 sync $JOT_LOCAL_DIR $JOT_S3_URL

sleep 5

printf "Pulling from S3...\n\n"
aws s3 sync $JOT_S3_URL $JOT_LOCAL_DIR
