#!/bin/bash

# flatcircle - fetch and view past log entries
# assumes $JOT_TERMINAL


# Pull jot configuration
source config

if [ ! -d $JOT_LOCAL_DIR ]; then
  mkdir -p $JOT_LOCAL_DIR
fi

YESTERDAY=`date -d "-1 day" +"%Y%m%d"`
FILE=$JOT_LOCAL_DIR/$YESTERDAY.md
if [ -f $FILE ]; then
  `$JOT_TERMINAL -x $JOT_EDITOR $FILE $GOYO`
fi

LASTWEEK=`date -d "-1 week" +"%Y%m%d"`
FILE=$JOT_LOCAL_DIR/$LASTWEEK.md
if [ -f $FILE ]; then
  `$JOT_TERMINAL -x $JOT_EDITOR $FILE $GOYO`
fi

LASTMONTH=`date -d "-1 month" +"%Y%m%d"`
FILE=$JOT_LOCAL_DIR/$LASTMONTH.md
if [ -f $FILE ]; then
  `$JOT_TERMINAL -x $JOT_EDITOR $FILE $GOYO`
fi

THREEMONTHSAGO=`date -d "-3 months" +"%Y%m%d"`
FILE=$JOT_LOCAL_DIR/$THREEMONTHSAGO.md
if [ -f $FILE ]; then
  `$JOT_TERMINAL -x $JOT_EDITOR $FILE $GOYO`
fi

SIXMONTHSAGO=`date -d "-6 months" +"%Y%m%d"`
FILE=$JOT_LOCAL_DIR/$SIXMONTHSAGO.md
if [ -f $FILE ]; then
  `$JOT_TERMINAL -x $JOT_EDITOR $FILE $GOYO`
fi

# All the years
for NUM_YEARS in {1..100}
do
    REVIEW_DOC=`date -d "-$NUM_YEARS year" +"%Y%m%d"`
    FILE=$JOT_LOCAL_DIR/$REVIEW_DOC.md
    if [ -f $FILE ]; then
        `$JOT_TERMINAL -x $JOT_EDITOR $FILE $GOYO`
    fi
done
