#!/bin/bash

# jot
# Make quick timestamped notes and log entries from the command line
# Access them from any terminal (thanks Amazon S3!)
# Author: Phaedrus

BR="\n"
BREAK="\n\n"
TAB="\t"
BUL="\t\t*"

DATE=`date +"%Y%m%d"`
TIME=`date +"%T"`
HEAD=`date +"%Y %b %d"`

NAME="phaedrusraznikov"
BUCKET="all-the-jots-for-$NAME"
DIR=~/Documents/jots/
FILE=$DIR/$DATE.md

if [ ! -d $DIR ]; then
  mkdir -p $DIR
fi

# Pull recent changes, if any
# Commented out until we solve the overwriting problem
# aws s3 sync s3://$BUCKET $DIR

if [ ! -f $FILE ]; then
  printf "# $HEAD" >> $FILE
fi

# set time header
printf "\n\n## $TIME\n\n" >> $FILE

# open logfile for writing
vi $FILE
