#!/bin/bash

# pull_remote_changes
# Pull jots from S3 before pushing local entries
# Author: Phaedrus

# Pull jot configuration
source ./config

printf "\nPulling from S3...\n"
aws s3 sync $JOT_S3_URL $JOT_LOCAL_DIR

sleep 5

printf "Pushing to S3...\n\n"
aws s3 sync $JOT_LOCAL_DIR $JOT_S3_URL
